development:
  adapter: solr
  url: <%= ENV['SOLR_DEV'] %>
test: &test
  adapter: solr
  url: http://localhost:<%= ENV['SOLR_TEST_PORT'] || 8985 %>/solr/hydra-test
production:
  adapter: solr
  url: <%= ENV['SOLR_PROD'] %>

