# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6cff532b02741f2b2fa4318d607b8b80c50aa1f991a2c50a1233d50fbc769a28ba322eab55775cb52a12f325c8ea959b70aa991420d5c9e49a2f271aa48f50e

test:
  secret_key_base: b222019e2e95856140e409ce4c3ff936c778923a3cdce80d4708ccb818a7382457697150e1baee0757072b5bfc2f4ea5f351f747205aadd84ad05d88b2a1a0be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
